{
 "title": "New dashboard",
 "time": { "from": "2023-03-01T00:00:00.000Z", "to": "2023-03-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Dummy - Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Quantile Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", quantile_value AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", num_drifted_columns AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", share_missing_values AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}